### PR TITLE
Arch migrator

### PR DESCRIPTION
**Pull request by martin-g**
This PR is based on https://github.com/conda-forge/tcsh-feedstock/pull/24 and fixes some lint errors

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by martin-g** [comment]
The OSX ARM64 build fails with:
```
2024-11-21T14:32:14.6078880Z 2024-11-21 14:32:14.605 xcodebuild[12137:37809] [MT] DVTSDK: Skipped SDK /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk; its version (11.0) is below required minimum (13.0) for the macosx platform.
2024-11-21T14:32:16.9467540Z 2024-11-21 14:32:16.946 xcodebuild[12137:37809] Writing error result bundle to /var/folders/p1/44pzfl0j2m301zzfb0fv0p380000gn/T/ResultBundle_2024-21-11_14-32-0016.xcresult
2024-11-21T14:32:18.2574550Z xcodebuild: error: SDK "/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk" cannot be located.
2024-11-21T14:32:18.6946740Z 2024-11-21 14:32:18.693 xcodebuild[12166:37915] [MT] DVTSDK: Skipped SDK /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk; its version (11.0) is below required minimum (13.0) for the macosx platform.
2024-11-21T14:32:19.7528170Z 2024-11-21 14:32:19.752 xcodebuild[12166:37915] Writing error result bundle to /var/folders/p1/44pzfl0j2m301zzfb0fv0p380000gn/T/ResultBundle_2024-21-11_14-32-0019.xcresult
2024-11-21T14:32:21.0683870Z xcodebuild: error: SDK "/Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk" cannot be located.
2024-11-21T14:32:23.6345700Z cc: error: sh -c '/Applications/Xcode_15.2.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode_15.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -find clang 2> /dev/null' failed with exit code 16384: (null) (errno=No such file or directory)
2024-11-21T14:32:23.6381870Z xcode-select: Failed to locate 'clang', requesting installation of command line developer tools.
```
I don't have experience with OSX toolchains. Any ideas ? Otherwise I will drop osx-arm64 from the build.

**Comment by martin-g** [comment]
@conda-forge-admin, please rerender

**Comment by bernt-matthias** [comment]
> Otherwise I will drop osx-arm64 from the build.

Fine for me.

**Comment by martin-g** [comment]
@conda-forge-admin, please ping team

**Review by bernt-matthias — APPROVED** [review]
Ready?

**Pull request merged**
