### PR TITLE
Add support for aarch64/ppc64le

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by jaimergp** [comment]
@bernt-matthias, I think this is ready for review!

**Comment by bernt-matthias** [comment]
Hi @jaimergp I just added the initial recipe (actually my 1st conda forge recipe) and think that I know to little to really judge this. 

Maybe we can recruit some body with more experience?

**Comment by jaimergp** [comment]
Fair enough! I have done the same in other packages for that PR you see mentioned some comments above, so the process is really straight forward:

1. Add `ppc64le` and `aarch64` provides in `/conda-forge.yml`.
2. Ask the bot to re-render the repo with `conda-smithy` tooling
3. Make sure tests are passing.
4. Merge.

In this case, I had to increase the build number because the recipe was slightly changed (to specify `make` as a build-time requirement), but I don't know if that's needed. Maybe we should ping @conda-forge/core to see if somebody has anything to add before you merge!

Thanks!

**Comment by CJ-Wright** [comment]
why didn't the bot open this pr?

**Comment by scopatz** [comment]
Maybe it wasn't added to the list of packages needed?

**Comment by jakirkham** [comment]
> Maybe it wasn't added to the list of packages needed?

Where is this list and how can we add things to it?

**Comment by bernt-matthias** [comment]
@jaimergp 

> 1. Add ppc64le and aarch64 provides in /conda-forge.yml.
> 3. Make sure tests are passing.

these points seem fulfilled

> Ask the bot to re-render the repo with conda-smithy tooling

Unfortunately I have no idea what this means :(

**Comment by jakirkham** [comment]
It looks like re-rendering was [done above]( https://github.com/conda-forge/tcsh-feedstock/pull/1#commits-pushed-9eb3152 ).

**Comment by bernt-matthias** [comment]
Then I will merge if no one disagrees.

**Comment by jakirkham** [comment]
SGTM. Thanks for the review! 😄

**Comment by jaimergp** [comment]
Thanks for the review!

**Comment by CJ-Wright** [comment]
@jakirkham the list is [here](https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators.xsh#L1118) and I'd happily merge a PR adding packages.

**Comment by jakirkham** [comment]
Thanks @CJ-Wright! Is that documented somewhere?

**Comment by CJ-Wright** [comment]
I don't know, cc @mariusvniekerk? Would you be interested in putting in a PR?

**Pull request merged**
